apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lobsters
  name: lobsters
spec:
  selector:
    matchLabels:
      app: lobsters
  replicas: 3
  template:
    metadata:
      labels:
        app: lobsters
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:2.1.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: database-url
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 500m
