apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    type: local
  finalizers: null
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mysql_data"
